# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'iOSFileSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSFileSystem

  target 'iOSFileSystemTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
