use_frameworks!

target 'iOSFileSystem_Example' do
  pod 'iOSFileSystem', :path => '../'

  target 'iOSFileSystem_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
